/** Course names transcribed from the linked published catalogue. Teaching notes,
 * timetable and attendance are synthetic demo material, not institutional records. */
export const curriculumSource = 'https://www.collegeadmission.in/notice/college/bitsom-admission-to-mba-programme-2026-2027-11982'
export const curriculumNotice = 'Published catalogue reference; current official curriculum unverified (BITSoM website returned 403). Cards are authored demo study material.'
export const courses = [
  ['Marketing Management', 1, 'How does segmentation differ from targeting?', 'Segmentation divides a market into groups with shared needs. Targeting selects the groups a business will serve.', 'What are the four Ps?', 'Product, price, place and promotion. They align the offering, cost, distribution and communication with the target customer.'],
  ['Business Statistics I', 1, 'When is the median preferable to the mean?', 'Use the median for skewed data or strong outliers because extreme values do not pull it as much as the mean.', 'What does standard deviation measure?', 'The spread of observations around their mean, expressed in the same units as the observations.'],
  ['Design Thinking', 1, 'Why prototype before building a full product?', 'A prototype tests assumptions quickly and cheaply with users, exposing misunderstandings before large investments.', 'What is an empathy interview?', 'An open-ended conversation to understand user needs, context and behaviour without leading them toward a preferred solution.'],
  ['Financial Accounting & Decision Making', 1, 'What is the accounting equation?', 'Assets = Liabilities + Equity. Every recorded transaction preserves this balance.', 'Why can a profitable firm run out of cash?', 'Profit includes accruals. Receivables, inventory purchases and debt payments can consume cash even when reported profit is positive.'],
  ['Operations Management', 1, 'What is a bottleneck?', 'The process step with the lowest effective capacity. It constrains the throughput of the whole system.', 'State Little’s law.', 'Average work in progress = average throughput × average flow time, for a stable process with consistent units.'],
  ['Corporate Finance I', 1, 'How do you calculate net present value?', 'Discount each future cash flow at the required return, then subtract the initial investment. Positive NPV indicates value creation under those assumptions.', 'What is the time value of money?', 'Money available today can earn a return. A future amount is discounted to compare it with money today.'],
  ['Decision Models & Uncertainty', 2, 'How is expected monetary value calculated?', 'Multiply each outcome by its probability and sum the products. It is a probability-weighted average, not a guaranteed result.', 'What does sensitivity analysis test?', 'How a decision or result changes when assumptions such as demand, cost or probabilities vary.'],
  ['Organisation Behaviour', 2, 'What is psychological safety?', 'A shared belief that a team permits interpersonal risks such as asking questions, admitting mistakes and raising concerns.', 'How does intrinsic motivation differ from extrinsic motivation?', 'Intrinsic motivation comes from interest or satisfaction in the work. Extrinsic motivation comes from external rewards or consequences.'],
  ['Business Statistics II', 2, 'What does a confidence interval describe?', 'An interval produced by a method that captures the fixed population parameter at the stated rate over repeated samples.', 'Does correlation prove causation?', 'No. Confounding variables, reverse causality or coincidence may explain an association. Causal claims need an appropriate design and assumptions.'],
  ['Entrepreneurship Foundations', 2, 'What is a minimum viable product?', 'The smallest usable offering that tests a critical business assumption with real customers and produces actionable learning.', 'What is product-market fit?', 'Evidence that a product satisfies strong demand in a defined market, often reflected in retention and repeated use or purchases.'],
  ['Digital Business and Innovation', 2, 'What is a network effect?', 'The value of a product to users changes as more users participate. Positive network effects can increase value with adoption.', 'How does a platform differ from a pipeline business?', 'A platform facilitates interactions among participant groups. A pipeline creates and delivers value through a more linear chain.'],
  ['Microeconomics', 2, 'What is opportunity cost?', 'The value of the best alternative forgone when making a choice.', 'What does price elasticity of demand measure?', 'Percentage change in quantity demanded divided by percentage change in price. Its magnitude indicates responsiveness to price changes.'],
  ['Business Drivers of Industry', 3, 'What are Porter’s five forces?', 'Competitive rivalry, threat of entry, threat of substitutes, supplier power and buyer power. Together they help analyse industry profit potential.', 'Why distinguish an industry trend from a company advantage?', 'An industry trend affects many firms; a company advantage depends on capabilities or positioning that support relative performance.'],
  ['Investment & Portfolio Management', 3, 'Why diversify a portfolio?', 'Combining imperfectly correlated assets can reduce asset-specific risk. It does not eliminate market risk.', 'What is portfolio expected return?', 'The sum of each asset’s expected return multiplied by its portfolio weight.'],
  ['Consumer Behaviour', 3, 'What is perceived risk in a purchase?', 'A consumer’s expectation of possible loss or uncertainty, such as financial, functional or social consequences.', 'How can social proof influence buying?', 'People may use others’ choices or reviews as information, especially when uncertain about product quality.'],
  ['Managerial Accounting', 3, 'What is contribution margin?', 'Sales revenue minus variable costs. It contributes toward covering fixed costs and then profit.', 'How do you calculate break-even units?', 'Fixed costs divided by contribution margin per unit, assuming a positive unit margin and constant cost and price assumptions.'],
  ['Competitive & Corporate Strategy', 3, 'How does competitive strategy differ from corporate strategy?', 'Competitive strategy concerns how to win in a business. Corporate strategy concerns which businesses to own and how the parent adds value.', 'What makes a resource strategically valuable?', 'It helps create customer value or reduce costs. Sustained advantage also depends on scarcity, difficulty of imitation and organisation.'],
  ['Negotiation Analysis', 3, 'What is BATNA?', 'Best alternative to a negotiated agreement: the strongest available option if the current negotiation fails.', 'What is a zone of possible agreement?', 'The overlap between the parties’ acceptable outcomes. If no overlap exists, an agreement requires changed terms or alternatives.']
].map(([name, term, q1, a1, q2, a2], i) => ({ id: `bitsom-${i+1}`, name: String(name), term: Number(term), cards: [{question:String(q1),answer:String(a1)}, {question:String(q2),answer:String(a2)}] }))

export function attendanceMath(attended: number, held: number, target: number) {
  if (![attended, held].every(Number.isSafeInteger) || attended < 0 || held < attended || !Number.isFinite(target) || target <= 0 || target > 100) throw new Error('Enter valid class counts and a target from 1 to 100.')
  const needed = target === 100 ? (attended === held ? 0 : null) : Math.max(0, Math.ceil((target * held - 100 * attended) / (100 - target)))
  const canMiss = Math.max(0, Math.floor((100 * attended - target * held) / target))
  return { percentage: held ? 100 * attended / held : null, needed, canMiss }
}
