import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { AuthenticateWithRedirectCallback, useAuth, useClerk, useSignIn } from '@clerk/react'
import { forceCenter, forceCollide, forceLink, forceManyBody, forceSimulation } from 'd3-force'
import { Activity, ArrowRight, BadgeIndianRupee, BookOpen, BookOpenCheck, BriefcaseBusiness, CalendarDays, Check, ChevronDown, ChevronRight, ClipboardCheck, Command, CreditCard, ExternalLink, FlaskConical, GraduationCap, Headphones, LayoutDashboard, ListChecks, LoaderCircle, LogOut, Menu, Mic2, Network, Presentation, Route as RouteIcon, Search, Send, Settings, Sparkles, Target, Telescope, Users, WalletCards, X, Zap } from 'lucide-react'
import { Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { createClient } from './api.js'
import { networkLinks, networkNodes, sampleJobs } from './network.js'

const navGroups = [
  ['Overview', [['/','Home dashboard',LayoutDashboard],['/pricing','Plans & pricing',CreditCard]]],
  ['Placements', [['/opportunities','On-campus jobs',BriefcaseBusiness],['/auto-apply','Auto-Apply',Send],['/interview','Interview AI',Mic2]]],
  ['Attendance', [['/timetable','Timetable',CalendarDays],['/attendance','Calculator',BookOpenCheck],['/class-priorities','Class priorities',Target]]],
  ['Semester planner', [['/planner','Semester plan',RouteIcon],['/progress','Daily progress',ListChecks],['/activity','Activity',Activity]]],
  ['Pending work', [['/assignments','Assignments',ClipboardCheck],['/fees','Fees',WalletCards]]],
  ['Exam prep', [['/quick-notes','Quick Notes',BookOpen],['/study','Study AI',Headphones],['/cue-cards','Cue-card library',GraduationCap]]],
  ['Exposure', [['/internships','Internships',Telescope],['/workshops','Live workshops',Presentation],['/faculty-projects','Faculty projects',FlaskConical],['/network','Industry network',Network]]],
  ['Account', [['/account','Profile & usage',Settings]]],
]

const exampleWorkspace = {
  profile: { target_role:'Associate Product Manager / Strategy Consultant', career_goal:'Build and lead category-defining technology products', salary_lpa:40, daily_minutes:180, specialisation:'Entrepreneurship & Innovation', skills:['Product strategy','SQL','Market research','Generative AI'], subjects:['Marketing Management','Business Statistics','Organisational Behaviour','Generative AI for Business'] },
  analytics: { tasks_completed:11, tasks_total:16, completion_percent:69, overdue:1, practice_sessions:5 },
  tasks: [
    { id:'1', title:'Turn the market-entry case into a one-page portfolio story', category:'project', status:'pending', due_at:new Date(Date.now()+86400000).toISOString(), minutes:50 },
    { id:'2', title:'Practice product sense: improve a campus workflow', category:'revision', status:'pending', due_at:new Date(Date.now()+172800000).toISOString(), minutes:35 },
    { id:'3', title:'Reach out to two operators from the fintech cluster', category:'networking', status:'done', due_at:new Date().toISOString(), minutes:20 },
  ],
  deadlines: [{ id:'d1', title:'Marketing Management — segmentation brief', category:'assignment', status:'pending', due_at:new Date(Date.now()+259200000).toISOString() }],
  assessments: [{ overall_score:78, readiness:74 }],
}

function useSage() {
  const auth = useAuth()
  const preview = import.meta.env.DEV && new URLSearchParams(location.search).get('preview') === '1'
  const client = useMemo(() => createClient(auth.getToken), [auth.getToken])
  return { ...auth, preview, client }
}

function Brand({ compact=false }) {
  return <div className={`brand ${compact?'brand--compact':''}`}><span className="brand-mark"><Sparkles size={19}/></span><span>SAGE</span>{!compact&&<small>move with clarity</small>}</div>
}

function GoogleIcon() {
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.6 12.2c0-.7-.1-1.4-.2-2H12v3.9h5.4a4.6 4.6 0 0 1-2 3v2.6h3.3c1.9-1.8 2.9-4.4 2.9-7.5Z"/><path fill="#34A853" d="M12 22c2.7 0 5-.9 6.7-2.3l-3.3-2.6c-.9.6-2.1 1-3.4 1a5.9 5.9 0 0 1-5.5-4.1H3.1v2.6A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.5 14a6 6 0 0 1 0-3.9V7.4H3.1a10 10 0 0 0 0 9.2L6.5 14Z"/><path fill="#EA4335" d="M12 6c1.5 0 2.8.5 3.9 1.5l2.9-2.8A9.7 9.7 0 0 0 3.1 7.4l3.4 2.7A5.9 5.9 0 0 1 12 6Z"/></svg>
}

function Landing() {
  const { signIn } = useSignIn()
  const [busy,setBusy] = useState(false)
  const startGoogle = async () => {
    if (!signIn) return
    setBusy(true)
    await signIn.authenticateWithRedirect({ strategy:'oauth_google', redirectUrl:'/sso-callback', redirectUrlComplete:'/' })
  }
  return <main className="landing">
    <header className="public-nav"><Brand/><button className="text-button" onClick={startGoogle}>Sign in <ArrowRight size={16}/></button></header>
    <section className="hero">
      <div className="hero-copy">
        <p className="eyebrow"><span/>Your ambition, operationalised</p>
        <h1>Know what<br/>moves you<br/><em>forward.</em></h1>
        <p className="hero-lede">SAGE connects your goals, classes, skills and real opportunities—then gives you the next move that matters.</p>
        <button className="google-button" disabled={busy||!signIn} onClick={startGoogle}>{busy?<LoaderCircle className="spin"/>:<GoogleIcon/>}<span>Continue with Google</span><ArrowRight size={18}/></button>
        <p className="microcopy">One sign-in. New members set up their path; returning members go straight home.</p>
      </div>
      <RouteCanvas/>
    </section>
    <section className="manifesto"><p>Built for the space between</p><h2>“I know what I want”<br/><span>and</span> “I know what to do today.”</h2></section>
    <section className="story-strip">
      <article><b>01</b><h3>See the whole picture</h3><p>Academics, attendance, applications and growth signals in one view.</p></article>
      <article><b>02</b><h3>Find real openings</h3><p>Live web research ranks five roles against your goals, proof and gaps.</p></article>
      <article><b>03</b><h3>Build useful momentum</h3><p>A daily plan turns ambition into work you can finish and show.</p></article>
    </section>
    <footer><Brand compact/><p>Strategic Action & Growth Engine</p><p>© {new Date().getFullYear()} SAGE</p></footer>
  </main>
}

function RouteCanvas() {
  return <div className="route-canvas" aria-label="A route connecting learning, people and opportunities">
    <div className="route-note">Your route · this week</div>
    <svg viewBox="0 0 620 620" role="img"><path className="route-line" d="M86 525 C150 430 90 335 205 290 S310 130 407 178 S520 277 530 83"/><path className="route-ghost" d="M90 525 C230 510 309 440 336 343 S420 269 530 83"/></svg>
    <div className="map-node node-you"><span>SK</span><strong>You</strong><small>high agency</small></div>
    <div className="map-node node-skill"><Zap/><strong>Applied AI</strong><small>skill to compound</small></div>
    <div className="map-node node-class"><BookOpen/><strong>Marketing</strong><small>today · 11:00</small></div>
    <div className="map-node node-role"><BriefcaseBusiness/><strong>5 role matches</strong><small>searched today</small></div>
    <div className="map-node node-person"><Users/><strong>Operator circle</strong><small>3 warm paths</small></div>
    <div className="route-stat"><b>73%</b><span>path readiness</span></div>
  </div>
}

function AuthGate() {
  const sage = useSage()
  const [state,setState] = useState(()=>sage.preview?{loading:false,me:{needs_onboarding:false,user:{full_name:'Sushruth Korada',email:'samsushruth@gmail.com'}},error:null}:{loading:true,me:null,error:null})
  useEffect(()=>{
    if (sage.preview || !sage.isLoaded) return
    if (!sage.isSignedIn) { queueMicrotask(()=>setState({loading:false,me:null,error:null})); return }
    sage.client.me().then(me=>setState({loading:false,me,error:null})).catch(error=>setState({loading:false,me:null,error}))
  },[sage.isLoaded,sage.isSignedIn,sage.preview,sage.client])
  if (state.loading || (!sage.isLoaded && !sage.preview)) return <FullLoader label="Opening your workspace"/>
  if (!sage.isSignedIn && !sage.preview) return <Landing/>
  if (state.error) return <ErrorState error={state.error}/>
  if (state.me?.needs_onboarding) return <Onboarding client={sage.client} me={state.me} onDone={()=>location.reload()}/>
  return <Workspace sage={sage} me={state.me}/>
}

function FullLoader({label}){return <div className="full-loader"><Brand/><div className="loader-orbit"><Sparkles/><i/></div><p>{label}</p></div>}
function ErrorState({error}){return <div className="error-state"><span>Something needs attention</span><h2>{error.message}</h2><button className="primary" onClick={()=>location.reload()}>Try again</button></div>}

function Onboarding({client,me,onDone}) {
  const [step,setStep]=useState(0), [catalog,setCatalog]=useState(null), [busy,setBusy]=useState(false)
  const [form,setForm]=useState({full_name:me?.user?.full_name||'',phone:'',program:'MBA',batch:2026,semester:1,specialisation:'Entrepreneurship & Innovation',subjects:[],target_role:'Associate Product Manager',career_goal:'Build and lead category-defining technology products',salary_lpa:35,daily_minutes:120,preferred_locations:['Mumbai','Bengaluru'],skills:['Strategy','Research']})
  useEffect(()=>{client.catalogue().then(setCatalog).catch(()=>setCatalog({specialisations:['Entrepreneurship & Innovation','Finance','Marketing'],courses:[]}))},[client])
  const update=(key,value)=>setForm(v=>({...v,[key]:value}))
  const submit=async()=>{setBusy(true);await client.completeOnboarding({full_name:form.full_name,phone:form.phone||null,mode:'student',goals:[form.career_goal],interests:['auto_apply','exam_prep'],call_consent:false,deadline_call_consent:false,profile:{...form,onboarding_version:2,institution_name:'BITSoM, Mumbai',graduation_year:2026,experience_summary:'MBA candidate building product, strategy and applied AI experience'}});onDone()}
  const steps=['Your direction','Your course','Your rhythm']
  return <main className="onboarding"><header><Brand/><div className="stepper">{steps.map((s,i)=><span key={s} className={i<=step?'active':''}>{String(i+1).padStart(2,'0')} {s}</span>)}</div></header>
    <section key={step} className="onboard-card onboard-enter">
      {step===0&&<><p className="eyebrow"><span/>Start with the outcome</p><h1>Where are you trying to go?</h1><div className="field-grid"><Field label="Your name"><input value={form.full_name} onChange={e=>update('full_name',e.target.value)}/></Field><Field label="Phone number"><input value={form.phone} placeholder="+91" onChange={e=>update('phone',e.target.value)}/></Field><Field wide label="Target role"><input value={form.target_role} onChange={e=>update('target_role',e.target.value)}/></Field><Field wide label="Career goal"><textarea value={form.career_goal} onChange={e=>update('career_goal',e.target.value)}/></Field><Field label="Dream salary (LPA)"><input type="number" value={form.salary_lpa} onChange={e=>update('salary_lpa',Number(e.target.value))}/></Field></div></>}
      {step===1&&<><p className="eyebrow"><span/>Build your academic context</p><h1>What are you learning now?</h1><div className="field-grid"><Field label="Programme"><select value={form.program} onChange={e=>update('program',e.target.value)}><option>MBA</option></select></Field><Field label="Graduating batch"><select value={form.batch} onChange={e=>update('batch',Number(e.target.value))}><option>2026</option><option>2027</option></select></Field><Field wide label="Specialisation"><select value={form.specialisation} onChange={e=>update('specialisation',e.target.value)}>{(catalog?.specialisations||[]).map(x=><option key={x}>{x}</option>)}</select></Field></div><p className="selection-label">Pick your current courses</p><div className="chips">{(catalog?.courses||[]).slice(0,16).map(c=><button key={c.title} className={form.subjects.includes(c.title)?'selected':''} onClick={()=>update('subjects',form.subjects.includes(c.title)?form.subjects.filter(x=>x!==c.title):[...form.subjects,c.title])}>{c.title}</button>)}</div></>}
      {step===2&&<><p className="eyebrow"><span/>Make the plan realistic</p><h1>How should SAGE work around you?</h1><div className="time-choice"><b>{form.daily_minutes}</b><span>minutes available each day</span><input aria-label="Minutes per day" type="range" min="30" max="300" step="15" value={form.daily_minutes} onChange={e=>update('daily_minutes',Number(e.target.value))}/></div><Field label="Preferred locations"><input value={form.preferred_locations.join(', ')} onChange={e=>update('preferred_locations',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></Field><p className="consent-copy">You control every application and call. SAGE uses this profile to rank opportunities, build your plan and personalise study support.</p></>}
      <div className="onboard-actions">{step>0&&<button className="secondary" onClick={()=>setStep(step-1)}>Back</button>}<button className="primary" disabled={busy||(step===1&&!form.subjects.length)} onClick={()=>step<2?setStep(step+1):submit()}>{busy?'Saving your path…':step<2?'Continue':'Enter SAGE'}<ArrowRight size={17}/></button></div>
    </section></main>
}

function Field({label,children,wide=false}){return <label className={wide?'wide':''}><span>{label}</span>{children}</label>}

function Workspace({sage,me}) {
  const [mobile,setMobile]=useState(false)
  const loc=useLocation(), navigate=useNavigate()
  const { signOut } = useClerk()
  return <div className="shell">
    <aside className={mobile?'open':''}><div className="rail-head"><Brand compact/><button className="icon-button mobile-only" onClick={()=>setMobile(false)}><X/></button><div className="campus-pill">BITSoM · MBA 2026</div></div><nav>{navGroups.map(([group,items])=><details key={group} open={items.some(([to])=>loc.pathname===to)||group==='Overview'}><summary>{group}<ChevronDown/></summary>{items.map(([to,label,Icon])=><button key={to} className={loc.pathname===to?'active':''} onClick={()=>{navigate(to);setMobile(false)}}><Icon/><span>{label}</span><ChevronRight/></button>)}</details>)}</nav><div className="rail-user"><span>{initials(me?.user?.full_name)}</span><div><strong>{me?.user?.full_name||'SAGE member'}</strong><small>{me?.user?.email}</small></div></div><button className="signout" onClick={()=>signOut()}><LogOut/>Sign out</button></aside>
    <header className="mobile-bar"><button className="icon-button" onClick={()=>setMobile(true)}><Menu/></button><Brand compact/><span>{initials(me?.user?.full_name)}</span></header>
    <main className="app-main"><Routes><Route path="/" element={<Dashboard sage={sage} me={me}/>}/><Route path="/pricing" element={<Pricing sage={sage}/>}/><Route path="/opportunities" element={<Opportunities sage={sage}/>}/><Route path="/auto-apply" element={<AutoApply sage={sage}/>}/><Route path="/interview" element={<InterviewAI sage={sage}/>}/><Route path="/network" element={<NetworkPage/>}/><Route path="/timetable" element={<Timetable sage={sage}/>}/><Route path="/attendance" element={<Attendance sage={sage}/>}/><Route path="/class-priorities" element={<ClassPriorities sage={sage}/>}/><Route path="/planner" element={<Planner sage={sage}/>}/><Route path="/progress" element={<Progress sage={sage}/>}/><Route path="/activity" element={<ActivityPlanner sage={sage}/>}/><Route path="/assignments" element={<PendingWork sage={sage} fees={false}/>}/><Route path="/fees" element={<PendingWork sage={sage} fees/>}/><Route path="/quick-notes" element={<QuickNotes sage={sage}/>}/><Route path="/study" element={<Study sage={sage}/>}/><Route path="/cue-cards" element={<CueCards sage={sage}/>}/><Route path="/internships" element={<Exposure type="internships"/>}/><Route path="/workshops" element={<Exposure type="workshops"/>}/><Route path="/faculty-projects" element={<Exposure type="faculty"/>}/><Route path="/account" element={<Account sage={sage} me={me}/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></main>
  </div>
}

function useWorkspace(sage){
  const [state,setState]=useState(()=>sage.preview?{loading:false,data:exampleWorkspace,error:null}:{loading:true,data:null,error:null})
  useEffect(()=>{if(sage.preview)return; sage.client.campus().then(data=>setState({loading:false,data,error:null})).catch(error=>setState({loading:false,data:null,error}))},[sage.preview,sage.client])
  return state
}

function PageHead({kicker,title,copy,action}){return <header className="page-head"><div><p className="eyebrow"><span/>{kicker}</p><h1>{title}</h1><p>{copy}</p></div>{action}</header>}

function Dashboard({sage,me}) {
  const {loading,data,error}=useWorkspace(sage)
  if(loading)return <PanelLoader label="Aligning your day"/>; if(error)return <ErrorState error={error}/>
  const a=data.analytics||{}, profile=data.profile||{}, first=(me?.user?.full_name||'there').split(' ')[0]
  const readiness=data.assessments?.[0]?.readiness||74
  return <div className="page-enter"><PageHead kicker="Friday · Your command view" title={`Good afternoon, ${first}.`} copy={`${profile.target_role||'Your next role'} · ${profile.daily_minutes||120} focused minutes available today`} action={<button className="command"><Command/>Ask SAGE <kbd>⌘ K</kbd></button>}/>
    <section className="pulse-grid"><article className="focus-card"><span className="card-index">01 · NEXT MOVE</span><h2>{data.tasks?.find(t=>t.status!=='done')?.title||'Build the first milestone in your action plan'}</h2><div><button className="dark-button">Start focus block <ArrowRight/></button><small>{data.tasks?.find(t=>t.status!=='done')?.minutes||45} minutes · highest leverage</small></div></article><article className="metric metric-lime"><small>Momentum</small><b>{a.completion_percent||0}<sup>%</sup></b><span>{a.tasks_completed||0} of {a.tasks_total||0} actions closed</span></article><article className="metric"><small>Career readiness</small><b>{readiness}<sup>%</sup></b><span>Portfolio proof is the next unlock</span></article><article className="metric metric-dark"><small>Attendance</small><b>76.7<sup>%</sup></b><span>3 classes above your safety line</span></article></section>
    <section className="dashboard-columns"><div><SectionTitle label="Today's route" action="Open planner"/><div className="timeline">{(data.tasks||[]).slice(0,4).map((t,i)=><div className={t.status==='done'?'done':''} key={t.id||i}><time>{new Date(t.due_at).toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}</time><i/>
      <span><strong>{t.title}</strong><small>{t.category} · {t.minutes||30} min</small></span>{t.status==='done'?<Check/>:<ArrowRight/>}</div>)}</div></div>
      <div className="signal-panel"><SectionTitle label="Signals worth seeing"/><div className="signal-big"><span>Role market</span><b>5 live matches</b><p>Your product + strategy profile is strongest in consumer tech and B2B software.</p><button onClick={()=>location.assign('/opportunities')}>Explore opportunities <ArrowRight/></button></div><div className="signal-row"><span><CalendarDays/> Next deadline</span><b>{data.deadlines?.[0]?.title||'No urgent deadlines'}</b></div><div className="signal-row"><span><Users/> Warm paths</span><b>3 people to learn from</b></div></div></section>
  </div>
}

function SectionTitle({label,action}){return <div className="section-title"><h2>{label}</h2>{action&&<button>{action}<ArrowRight/></button>}</div>}
function PanelLoader({label}){return <div className="panel-loader"><LoaderCircle className="spin"/><p>{label}</p></div>}

function Opportunities({sage}) {
  const [filters,setFilters]=useState({role:'',location:'Mumbai, Bengaluru or remote India',work_mode:'any'})
  const [state,setState]=useState({busy:false,items:sage.preview?sampleJobs:[],meta:null,error:null})
  const discover=async()=>{setState(s=>({...s,busy:true,error:null}));try{if(sage.preview){await new Promise(r=>setTimeout(r,900));setState({busy:false,items:sampleJobs,meta:{summary:'Three strong matches selected from current profile signals.',searched_at:new Date().toISOString()},error:null})}else{const data=await sage.client.discoverJobs(filters);setState({busy:false,items:data.items,meta:data,error:null})}}catch(error){setState(s=>({...s,busy:false,error}))}}
  return <><PageHead kicker="Opportunity intelligence" title="Five roles worth your attention." copy="SAGE searches the live web, opens the sources and ranks verified openings against your direction and evidence." action={<button className="primary" onClick={discover} disabled={state.busy}>{state.busy?<LoaderCircle className="spin"/>:<Search/>}{state.busy?'Searching the live web…':'Find my 5 roles'}</button>}/>
    <section className="search-console"><div><Field label="Role direction"><input placeholder="Use my profile" value={filters.role} onChange={e=>setFilters({...filters,role:e.target.value})}/></Field><Field label="Where"><input value={filters.location} onChange={e=>setFilters({...filters,location:e.target.value})}/></Field><Field label="Work mode"><select value={filters.work_mode} onChange={e=>setFilters({...filters,work_mode:e.target.value})}><option value="any">Any</option><option value="hybrid">Hybrid</option><option value="remote">Remote</option><option value="onsite">On-site</option></select></Field></div><p><Sparkles/> Search reads your target role, skills, experience and salary goal. Every result links back to the page inspected.</p></section>
    {state.error&&<div className="inline-error">{state.error.message}</div>}
    {state.busy&&<SearchProgress/>}
    {!state.busy&&!state.items.length&&<EmptyJobs onClick={discover}/>} 
    {!state.busy&&state.items.length>0&&<section className="job-list"><div className="job-list-head"><p>{state.meta?.summary||'Profile-fit shortlist'}</p><span>{state.meta?.searched_at?`Updated ${new Date(state.meta.searched_at).toLocaleString('en-IN')}`:'Ready to refresh from the live web'}</span></div>{state.items.map((job,i)=><JobCard key={`${job.company}-${job.title}`} job={job} rank={i+1}/>)}</section>}
  </>
}

function SearchProgress(){return <div className="search-progress"><div className="scanner"><i/><Search/></div><div><h3>Searching beyond job titles</h3><p>Opening source pages · checking role details · scoring profile fit · selecting the strongest five</p></div></div>}
function EmptyJobs({onClick}){return <div className="empty-jobs"><span><Search/></span><h2>Your live shortlist starts here.</h2><p>Run a search and SAGE will return up to five source-backed roles aligned to your current profile.</p><button className="dark-button" onClick={onClick}>Search now <ArrowRight/></button></div>}
function JobCard({job,rank}){return <article className="job-card"><div className="job-rank">{String(rank).padStart(2,'0')}</div><div className="job-main"><p>{job.company}</p><h2>{job.title}</h2><div className="job-meta"><span>{job.location}</span><span>{job.work_mode}</span><span>{job.employment_type}</span>{job.salary&&<span>{job.salary}</span>}</div><div className="skill-row">{job.skills?.slice(0,5).map(s=><span key={s}>{s}</span>)}</div></div><div className="fit-score"><b>{job.match_score}</b><small>profile fit</small></div><div className="job-reason"><strong>Why it fits</strong>{job.why_it_fits?.map(x=><p key={x}><Check/>{x}</p>)}{job.gaps?.[0]&&<p className="gap"><Zap/>{job.gaps[0]}</p>}</div><a className="source-link" href={job.apply_url||job.source_url} target="_blank" rel="noreferrer">View source & apply <ExternalLink/></a></article>}

function NetworkPage(){return <><PageHead kicker="Opportunity graph" title="Your network is a route, not a list." copy="Explore how your skills, work and people connect to the opportunities you want."/><section className="network-layout"><NetworkGraph/><aside className="network-legend"><p>Connection types</p>{[['self','You'],['founder','Founders'],['student','Students'],['leader','Industry leaders'],['skill','Skills'],['project','Proof of work'],['opportunity','Opportunities']].map(([type,label])=><span key={type}><i className={type}/>{label}</span>)}<div><Sparkles/><strong>Suggested move</strong><p>Use the Market-entry sprint to start a conversation with the fintech founder cluster.</p><button>Build outreach plan <ArrowRight/></button></div></aside></section></>}

function NetworkGraph(){
  const ref=useRef(null), [points,setPoints]=useState([]), [selected,setSelected]=useState(networkNodes[0])
  const build=useCallback(()=>{const width=ref.current?.clientWidth||800,height=Math.max(560,ref.current?.clientHeight||620);const nodes=networkNodes.map(n=>({...n})),links=networkLinks.map(l=>({...l}));const sim=forceSimulation(nodes).force('link',forceLink(links).id(d=>d.id).distance(d=>d.source.id==='you'||d.target.id==='you'?130:105).strength(.6)).force('charge',forceManyBody().strength(-460)).force('center',forceCenter(width/2,height/2)).force('collision',forceCollide().radius(d=>d.id==='you'?62:45)).stop();for(let i=0;i<240;i++)sim.tick();setPoints(nodes.map(n=>({...n,x:Math.max(60,Math.min(width-60,n.x)),y:Math.max(60,Math.min(height-60,n.y))})))},[])
  useEffect(()=>{build();const ro=new ResizeObserver(build);if(ref.current)ro.observe(ref.current);return()=>ro.disconnect()},[build])
  const point=Object.fromEntries(points.map(n=>[n.id,n]));return <div className="graph" ref={ref}><svg width="100%" height="100%">{networkLinks.map((l,i)=>point[l.source]&&point[l.target]?<line key={i} x1={point[l.source].x} y1={point[l.source].y} x2={point[l.target].x} y2={point[l.target].y}/>:null)}{points.map(n=><g key={n.id} transform={`translate(${n.x},${n.y})`} className={`graph-node ${n.type} ${selected.id===n.id?'selected':''}`} onClick={()=>setSelected(n)}><circle r={n.id==='you'?34:25}/><text textAnchor="middle" y={n.id==='you'?56:46}>{n.label}</text></g>)}</svg><div className="graph-detail"><span>{selected.type}</span><strong>{selected.label}</strong><p>{selected.detail}</p></div></div>
}

function Academics({sage}){const {loading,data,error}=useWorkspace(sage);if(loading)return <PanelLoader label="Reading your academic week"/>;if(error)return <ErrorState error={error}/>;const subjects=data.profile?.subjects||[];return <><PageHead kicker="Academics & attendance" title="Protect the classes that compound." copy="See your week, attendance safety line and how each subject supports your target role."/><section className="academic-grid"><article className="attendance-ring"><div><b>76.7%</b><span>current attendance</span></div><h3>Your safety line is visible.</h3><p>Attend the next 5 scheduled classes to reach 78.1%. You can miss 3 of the following 22 classes and stay above 75%.</p></article><article className="course-stack"><SectionTitle label="Role-relevant subjects"/>{subjects.slice(0,5).map((s,i)=><div key={s}><span>{String(i+1).padStart(2,'0')}</span><strong>{s}</strong><small>{i<2?'High career relevance':'Core academic value'}</small><i style={{width:`${92-i*9}%`}}/></div>)}</article><article className="week-panel"><SectionTitle label="This week"/>{['Mon','Tue','Wed','Thu','Fri'].map((d,i)=><div key={d}><b>{d}</b><span>{subjects[i%Math.max(1,subjects.length)]||'MBA core class'}</span><small>{9+i%3*2}:00</small></div>)}</article></section></>}

function Planner({sage}){const [goal,setGoal]=useState('Build an interview-ready product portfolio and secure a high-growth role'),[busy,setBusy]=useState(false),[plan,setPlan]=useState(null);const generate=async()=>{setBusy(true);try{if(sage.preview){await new Promise(r=>setTimeout(r,700));setPlan({title:'8-week product proof sprint',summary:'Build one credible product case, sharpen analytical evidence and create focused conversations with operators.',milestones:[{week:1,title:'Direction locked',evidence:'Role thesis and gap map'},{week:3,title:'Proof shipped',evidence:'Published product case'},{week:6,title:'Interview ready',evidence:'Two scored mock interviews'}],tasks:exampleWorkspace.tasks})}else{const r=await sage.client.generatePlan({kind:'semester',goal,weeks:8,focus:'placements'});setPlan(r.output)}}finally{setBusy(false)}};return <><PageHead kicker="AI action planning" title="Turn the goal into a route you can finish." copy="SAGE fits learning, proof, applications and networking into the time you actually have." action={<button className="primary" onClick={generate} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Sparkles/>}{busy?'Designing your route…':'Build my plan'}</button>}/><section className="plan-builder"><Field label="The outcome I want"><textarea value={goal} onChange={e=>setGoal(e.target.value)}/></Field><div className="plan-controls"><span>8 weeks</span><span>Placements</span><span>Uses your daily time budget</span></div></section>{plan&&<section className="plan-result"><p>YOUR ROUTE</p><h2>{plan.title}</h2><p>{plan.summary}</p><div>{plan.milestones?.map((m,i)=><article key={m.title}><b>W{m.week||i+1}</b><span><strong>{m.title}</strong><small>{m.evidence}</small></span></article>)}</div></section>}</>}

function AutoApply({sage}){
 const [url,setUrl]=useState(''),[resume,setResume]=useState('Sushruth Korada — MBA candidate focused on product strategy, analytics and applied AI.'),[running,setRunning]=useState(false),[apps,setApps]=useState(()=>JSON.parse(localStorage.getItem('sage:web:applications')||'[]'))
 const start=async()=>{setRunning(true);if(!sage.preview)await sage.client.autoApplyStatus();await new Promise(r=>setTimeout(r,700));const item={id:crypto.randomUUID(),url,status:'review_required',title:new URL(url).hostname,created_at:new Date().toISOString()};const next=[item,...apps];setApps(next);localStorage.setItem('sage:web:applications',JSON.stringify(next));setRunning(false)}
 return <><PageHead kicker="Placements · supervised automation" title="Apply faster. Stay in control." copy="Paste a role link. SAGE prepares the application from your saved profile and stops for your review before any submission."/><section className="apply-layout"><div className="apply-form"><Field label="Job or internship link"><input type="url" placeholder="https://company.com/jobs/…" value={url} onChange={e=>setUrl(e.target.value)}/></Field><Field label="Resume profile used for this application"><textarea value={resume} onChange={e=>setResume(e.target.value)}/></Field><div className="safety-line"><Check/> Sign-in, CAPTCHA, sensitive questions and final submission always wait for you.</div><button className="primary" disabled={running||!url.startsWith('http')} onClick={start}>{running?<LoaderCircle className="spin"/>:<Send/>}{running?'Preparing application…':'Prepare application'}</button></div><div className="application-queue"><SectionTitle label="Application queue"/>{apps.length?apps.map(a=><article key={a.id}><span><BriefcaseBusiness/></span><div><strong>{a.title}</strong><small>{a.url}</small></div><b>Review needed</b></article>):<p>No applications queued yet.</p>}</div></section></>
}

function InterviewAI({sage}){
 const [role,setRole]=useState('Associate Product Manager'),[jd,setJd]=useState(''),[resume,setResume]=useState('MBA candidate with product strategy, SQL, research and applied AI project experience.'),[deck,setDeck]=useState(null),[busy,setBusy]=useState(false),[phone,setPhone]=useState('+919300641352'),[consent,setConsent]=useState(false),[message,setMessage]=useState('')
 const prepare=async()=>{setBusy(true);try{if(sage.preview){await new Promise(r=>setTimeout(r,650));setDeck({id:'preview-interview',title:`${role} interview room`,cards:[{front:'Tell me about a product decision you made with incomplete information.',back:'Use a concise situation, evidence, decision, trade-off and measurable outcome.'},{front:'How would you improve activation for a new B2B product?',back:'Define activation, segment users, inspect the funnel, identify friction, form hypotheses and prioritize experiments.'}]})}else setDeck(await sage.client.createDeck({topic:`Interview practice: ${role}`,level:'MBA placement interview',exam:'Mock interview',count:8,notes:`RESUME\n${resume}\nJOB DESCRIPTION\n${jd}`}))}finally{setBusy(false)}}
 const call=async()=>{if(!consent||!deck)return;setBusy(true);try{if(sage.preview){setMessage(`Interview call requested to ${phone.slice(0,3)}••••••${phone.slice(-2)}.`)}else{const r=await sage.client.request('POST','/v1/exam-prep/calls',{deck_id:deck.id,destination:phone,consent:true,consent_version:'v1',idempotency_key:crypto.randomUUID()});setMessage(`Call ${r.status}. Keep your phone nearby.`)}}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return <><PageHead kicker="Placements · Interview AI" title="Practice against the role you want." copy="Ground the interview in your resume and the job description, then get structured questions and a voice practice session."/><section className="interview-grid"><div className="stack-card"><Field label="Role"><input value={role} onChange={e=>setRole(e.target.value)}/></Field><Field label="Job description"><textarea placeholder="Paste the JD" value={jd} onChange={e=>setJd(e.target.value)}/></Field><Field label="Resume context"><textarea value={resume} onChange={e=>setResume(e.target.value)}/></Field><button className="primary" onClick={prepare} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Sparkles/>}Build interview</button></div><div className="interview-room">{deck?<><p>READY ROOM</p><h2>{deck.title}</h2>{deck.cards?.slice(0,2).map(c=><div key={c.front}><strong>{c.front}</strong><small>{c.back}</small></div>)}<Field label="Call this number"><input value={phone} onChange={e=>setPhone(e.target.value)}/></Field><label className="checkline"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I agree to receive this AI practice call and have it transcribed for my assessment.</label><button className="dark-button" disabled={!consent||busy} onClick={call}><Mic2/>Start voice interview</button>{message&&<p className="status-note">{message}</p>}</>:<div className="room-empty"><Mic2/><h3>Your interview room will appear here.</h3><p>SAGE builds questions from the exact role and your experience.</p></div>}</div></section></>
}

function Timetable({sage}){const {loading,data,error}=useWorkspace(sage);if(loading)return <PanelLoader label="Loading your timetable"/>;if(error)return <ErrorState error={error}/>;const subjects=data.profile?.subjects||[];return <><PageHead kicker="Attendance · calendar" title="Your week, before it gets busy." copy="Classes, assignment deadlines and focused work blocks share one view."/><section className="calendar-board">{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((day,i)=><article key={day}><header><span>{day.slice(0,3)}</span><b>{28+i}</b></header>{i<5&&[0,1].map(j=><div className={j?'class-event violet':'class-event lime'} key={j}><small>{j?'11:00':'09:00'}–{j?'12:30':'10:30'}</small><strong>{subjects[(i*2+j)%Math.max(1,subjects.length)]||'MBA core course'}</strong></div>)}{data.deadlines?.filter(d=>new Date(d.due_at).getDay()===(i+1)%7).map(d=><div className="class-event coral" key={d.id}><small>Deadline</small><strong>{d.title}</strong></div>)}</article>)}</section></>}

function Attendance({sage}){const {loading,data,error}=useWorkspace(sage);const [target,setTarget]=useState(75),[future,setFuture]=useState(236),[willAttend,setWillAttend]=useState(170),[rows,setRows]=useState([['Marketing Management',17,22],['Business Statistics',19,24],['Organisational Behaviour',16,21],['Generative AI for Business',18,21]]);if(loading)return <PanelLoader label="Calculating attendance"/>;if(error)return <ErrorState error={error}/>;const attended=rows.reduce((a,r)=>a+r[1],0),held=rows.reduce((a,r)=>a+r[2],0),pct=100*attended/held,needed=pct>=target?0:Math.ceil((target*held-100*attended)/(100-target)),projected=100*(attended+willAttend)/(held+future);return <><PageHead kicker="Attendance · live calculator" title="Know exactly what the next class changes." copy={`${data.profile?.target_role||'Your goal'} stays connected to the classes that build the strongest evidence.`}/><section className="attendance-dashboard"><article className="attendance-summary"><div><b>{pct.toFixed(1)}%</b><span>{attended} attended · {held} held</span></div><Field label="Target attendance"><select value={target} onChange={e=>setTarget(Number(e.target.value))}>{[75,80,85,90].map(x=><option key={x}>{x}</option>)}</select></Field><h3>{needed?`Attend the next ${needed} classes consecutively to reach ${target}%.`:`You are at or above your ${target}% target.`}</h3></article><article className="scenario"><h2>Future scenario</h2><div><Field label="Upcoming classes"><input type="number" value={future} onChange={e=>setFuture(Number(e.target.value))}/></Field><Field label="Classes you attend"><input type="number" value={willAttend} onChange={e=>setWillAttend(Number(e.target.value))}/></Field></div><b>{projected.toFixed(1)}%</b><p>Attend {willAttend} of the next {future} classes → {attended+willAttend} / {held+future} overall.</p></article></section><section className="attendance-rows">{rows.map((r,i)=><article key={r[0]}><div><strong>{r[0]}</strong><small>{r[1]} of {r[2]} classes</small></div><b>{(100*r[1]/r[2]).toFixed(1)}%</b><button onClick={()=>setRows(rows.map((x,j)=>j===i?[x[0],x[1]+1,x[2]+1]:x))}>Attended</button><button onClick={()=>setRows(rows.map((x,j)=>j===i?[x[0],x[1],x[2]+1]:x))}>Missed</button></article>)}</section></>}

function ClassPriorities({sage}){const {loading,data,error}=useWorkspace(sage);if(loading)return <PanelLoader label="Mapping classes to your goal"/>;if(error)return <ErrorState error={error}/>;return <><PageHead kicker="Attendance · recommendations" title="Attend for the skills, not just the percentage." copy="Classes are ranked against your role direction, target salary and current evidence gaps."/><section className="priority-list">{(data.profile?.subjects||[]).slice(0,6).map((s,i)=><article key={s}><span>{String(i+1).padStart(2,'0')}</span><div><h2>{s}</h2><p>{i<2?'Directly builds product judgment, analytical reasoning and interview stories.':'Protects core academic performance and adds useful business context.'}</p></div><b>{Math.max(66,95-i*6)}<small>% relevance</small></b><em>{i<3?'Priority attend':'Attend when possible'}</em></article>)}</section></>}

function Progress({sage}){const {loading,data,error}=useWorkspace(sage);if(loading)return <PanelLoader label="Loading progress"/>;if(error)return <ErrorState error={error}/>;const tasks=data.tasks||[],done=tasks.filter(t=>t.status==='done').length;return <><PageHead kicker="Semester planner · progress" title="Momentum you can inspect." copy="Every task closes a gap in learning, proof, applications or relationships."/><section className="progress-hero"><div><small>SEMESTER COMPLETION</small><b>{tasks.length?Math.round(done/tasks.length*100):0}%</b><span>{done} of {tasks.length} actions complete</span></div><div className="bar-chart">{[42,58,52,74,68,86,77,93].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></section><section className="task-board">{['pending','done'].map(status=><div key={status}><h2>{status==='pending'?'Next actions':'Completed'}</h2>{tasks.filter(t=>t.status===status).map(t=><article key={t.id}><span>{t.category}</span><strong>{t.title}</strong><small>{t.minutes} min</small></article>)}</div>)}</section></>}

function ActivityPlanner({sage}){const [focus,setFocus]=useState('Build a product portfolio and meaningful operator relationships'),[plan,setPlan]=useState(null),[busy,setBusy]=useState(false);const go=async()=>{setBusy(true);try{if(sage.preview){await new Promise(r=>setTimeout(r,600));setPlan([{type:'Project',title:'Campus experience teardown',proof:'One public case study with metrics and trade-offs'},{type:'Networking',title:'Operator learning loop',proof:'Four focused conversations and a synthesis note'},{type:'Internship',title:'Founder’s office sprint',proof:'A shipped market or product workstream'}])}else{const r=await sage.client.generatePlan({kind:'activity',goal:focus,weeks:8,focus:'portfolio and exposure'});setPlan(r.output.tasks)}}finally{setBusy(false)}};return <><PageHead kicker="Semester planner · activity" title="Turn learning into things people can see." copy="Select an outcome and SAGE structures projects, internships, networking and real-world use cases." action={<button className="primary" onClick={go} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Sparkles/>}Generate activities</button>}/><div className="plan-builder"><Field label="What should this semester prove?"><textarea value={focus} onChange={e=>setFocus(e.target.value)}/></Field></div>{plan&&<section className="activity-cards">{plan.slice(0,6).map((x,i)=><article key={x.title||i}><span>{x.type||x.category}</span><h2>{x.title}</h2><p>{x.proof||x.deliverable}</p><ArrowRight/></article>)}</section>}</>}

function PendingWork({sage,fees}){const {loading,data,error}=useWorkspace(sage);const [title,setTitle]=useState(''),[due,setDue]=useState('');if(loading)return <PanelLoader label="Loading pending work"/>;if(error)return <ErrorState error={error}/>;const list=(data.deadlines||[]).filter(d=>fees?d.category!=='assignment':d.category==='assignment');const add=async()=>{if(sage.preview)return;await sage.client.addDeadline({title,category:'assignment',due_at:new Date(due).toISOString(),amount:0});location.reload()};return <><PageHead kicker={fees?'Pending work · fees':'Pending work · faculty assignments'} title={fees?'Payments without surprises.':'Deadlines, clearly owned.'} copy={fees?'Track academic and transport fees, verified payment status and due dates.':'See what is pending, when it is due and the next action required.'}/>{!fees&&<section className="deadline-add"><Field label="Assignment"><input value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Due date"><input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></Field><button className="primary" disabled={!title||!due} onClick={add}>Add assignment</button></section>}<section className="deadline-list">{list.map((d,i)=><article key={d.id||i}><span className={d.status}>{d.status}</span><div><h2>{d.title}</h2><p>Due {new Date(d.due_at).toLocaleString('en-IN')}</p></div>{fees?<b>₹{((d.amount||0)/100).toLocaleString('en-IN')}</b>:<button className="secondary" onClick={()=>!sage.preview&&sage.client.completeDeadline(d.id)}>Mark complete</button>}</article>)}{!list.length&&<div className="empty-row">Nothing pending here.</div>}</section></>}

function QuickNotes({sage}){const [topic,setTopic]=useState('Segmentation and targeting'),[notes,setNotes]=useState(''),[deck,setDeck]=useState(null),[busy,setBusy]=useState(false);const create=async()=>{setBusy(true);try{if(sage.preview){await new Promise(r=>setTimeout(r,650));setDeck({title:'Segmentation & targeting — rapid review',summary:'The exam-ready distinctions, frameworks and common errors.',quick_tips:['Define the market before segmenting','Use measurable variables','Explain why a target is attractive'],common_mistakes:['Confusing a segment with a persona','Choosing every segment'],cards:[{front:'What makes a market segment useful?',back:'It should be measurable, substantial, accessible, differentiable and actionable.'},{front:'Segmentation vs targeting?',back:'Segmentation creates meaningful groups; targeting evaluates them and chooses which to serve.'}]})}else setDeck(await sage.client.createDeck({topic,level:'MBA',exam:'BITSoM course assessment',count:12,notes:notes||null}))}finally{setBusy(false)}};return <><PageHead kicker="Exam prep · Quick Notes" title="From topic to exam-ready structure." copy="Choose a subject and topic, add your own material if needed, and generate concise notes with cue cards." action={<button className="primary" onClick={create} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Sparkles/>}Generate</button>}/><section className="notes-builder"><Field label="Topic"><input value={topic} onChange={e=>setTopic(e.target.value)}/></Field><Field label="Your notes or syllabus (optional)"><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Paste source material to ground the output"/></Field></section>{deck&&<DeckDisplay deck={deck}/>}</>}

function CueCards({sage}){const previewDecks=[{id:'sample',title:'Marketing Management',cards:[{front:'How is segmentation different from targeting?',back:'Segmentation groups the market; targeting chooses which groups to serve.'},{front:'What is positioning?',back:'The distinct place a brand aims to occupy in the target customer’s mind.'}]}];const [decks,setDecks]=useState(()=>sage.preview?previewDecks:[]),[quiz,setQuiz]=useState(false),[reveal,setReveal]=useState(false),[index,setIndex]=useState(0);useEffect(()=>{if(sage.preview)return;sage.client.decks().then(r=>Promise.all(r.items.slice(0,5).map(d=>sage.client.deck(d.id))).then(setDecks)).catch(()=>setDecks([]))},[sage]);const cards=decks.flatMap(d=>(d.cards||[]).map(c=>({...c,deck:d.title})));const card=cards[index%Math.max(1,cards.length)];return <><PageHead kicker="Exam prep · library" title="Questions and answers, together." copy="Browse complete cue cards or switch to quiz mode when you want active recall." action={<button className="secondary" onClick={()=>{setQuiz(!quiz);setReveal(false)}}>{quiz?'Show full cards':'Start quiz'}</button>}/>{!quiz?<section className="card-library">{cards.map((c,i)=><article key={c.id||i}><span>{c.deck}</span><small>QUESTION</small><h2>{c.front}</h2><small>ANSWER</small><p>{c.back}</p></article>)}</section>:card?<section className="quiz-card"><span>{card.deck} · {index+1}/{cards.length}</span><h2>{card.front}</h2>{reveal&&<p>{card.back}</p>}<div><button className="secondary" onClick={()=>setReveal(!reveal)}>{reveal?'Hide answer':'Reveal answer'}</button>{reveal&&<button className="primary" onClick={()=>{setIndex(index+1);setReveal(false)}}>Next card <ArrowRight/></button>}</div></section>:<div className="empty-row">Generate a Quick Notes deck first.</div>}</>}

function Study(){const [answer,setAnswer]=useState(false);return <><PageHead kicker="Study AI" title="Practice until the answer becomes yours." copy="Move from quick notes to recall, spoken questions and a clear readiness signal."/><section className="study-stage"><div className="study-menu"><span className="active">01 · Cue cards</span><span>02 · Spoken practice</span><span>03 · Readiness</span></div><article className="cue-card" onClick={()=>setAnswer(!answer)}><div><span>Marketing Management · Card 04 / 12</span><button>{answer?'Hide answer':'Reveal answer'}</button></div><p>{answer?'Segmentation divides a broad market into meaningful groups with shared needs or behaviours. Targeting evaluates those groups and chooses which ones the organisation will serve.':'How is market segmentation different from targeting?'}</p><small>{answer?'Answer shown · click anywhere to return to the question':'Think first. Then reveal the answer.'}</small></article><div className="study-stats"><span><b>78%</b>ready</span><span><b>3</b>weak topics</span><span><b>5</b>sessions</span></div></section></>}

function DeckDisplay({deck}){return <section className="deck-output"><div><span>QUICK NOTES</span><h2>{deck.title}</h2><p>{deck.summary}</p><ul>{deck.quick_tips?.map(x=><li key={x}>{x}</li>)}</ul></div><div><span>COMMON MISTAKES</span>{deck.common_mistakes?.map(x=><p key={x}>{x}</p>)}</div></section>}

const exposure={internships:[['Founder’s Office Intern','Consumer technology · Mumbai','Build market and product strategy directly with the founding team.'],['Product Strategy Intern','B2B SaaS · Bengaluru','Own research, activation analysis and one experiment.'],['Venture Fellow','Early-stage fund · Hybrid','Map a sector and support founder diligence.']],workshops:[['Product teardown live lab','Saturday · 11:00 IST','Work with operators to critique and redesign a real activation flow.'],['AI prototyping sprint','Wednesday · 18:30 IST','Build a working internal tool from an MBA use case.'],['Consulting case room','Friday · 17:00 IST','Practice market entry and profitability cases with peers.']],faculty:[['Applied AI in organisations','Faculty collaboration · 6 weeks','Research how teams adopt AI systems and measure behaviour change.'],['Consumer decision lab','Marketing faculty · 4 weeks','Support an experiment on choice architecture and positioning.'],['Emerging markets research','Strategy faculty · 8 weeks','Build a structured company and sector evidence base.']]}
function Exposure({type}){const titles={internships:['Exposure · internships','Work where the learning is real.'],workshops:['Exposure · live workshops','Learn beside people doing the work.'],faculty:['Exposure · faculty projects','Build knowledge with faculty.']};return <><PageHead kicker={titles[type][0]} title={titles[type][1]} copy="Selected against your course, role direction and evidence gaps."/><section className="exposure-grid">{exposure[type].map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,'0')}</span><h2>{x[0]}</h2><b>{x[1]}</b><p>{x[2]}</p><button>View opportunity <ArrowRight/></button></article>)}</section></>}

function Pricing({sage}){const previewPlans=[{code:'plus',name:'Plus',price_inr_paise:79900,description:'Build academic momentum',features:['Semester planning','Exam prep','Live job search']},{code:'pro',name:'Pro',price_inr_paise:149900,description:'Accelerate placements',features:['Everything in Plus','Auto-Apply','Interview AI']},{code:'ultra',name:'Ultra',price_inr_paise:249900,description:'Your complete action engine',features:['Everything in Pro','More voice minutes','Priority AI usage']}];const [plans,setPlans]=useState(()=>sage.preview?previewPlans:[]);useEffect(()=>{if(sage.preview)return;sage.client.plans().then(r=>setPlans(r.items)).catch(()=>setPlans([]))},[sage]);return <><PageHead kicker="Plans & pricing" title="Choose how much momentum you want." copy="Every plan keeps application submission, sensitive fields and calls under your control."/><section className="pricing-grid">{plans.map((p,i)=><article className={i===1?'featured':''} key={p.code}><span>{i===1?'MOST CHOSEN':p.name}</span><h2>{p.name}</h2><p>{p.description}</p><b>₹{Math.round(p.price_inr_paise/100).toLocaleString('en-IN')}<small>/ month</small></b><ul>{(p.features||[]).slice(0,7).map(f=><li key={f}><Check/>{String(f).replaceAll('_',' ')}</li>)}</ul><button className={i===1?'primary':'secondary'}>Choose {p.name}</button></article>)}</section></>}

function Account({sage,me}){const [name,setName]=useState(me?.user?.full_name||''),[phone,setPhone]=useState(me?.user?.phone||'+919300641352'),[msg,setMsg]=useState('');const save=async()=>{try{if(!sage.preview)await sage.client.updateMe({full_name:name,phone});setMsg('Profile saved')}catch(e){setMsg(e.message)}};const sub=me?.subscription;return <><PageHead kicker="Account" title="Your profile powers every recommendation." copy={me?.user?.email}/><section className="account-grid"><article><h2>Profile</h2><Field label="Name"><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Phone for consented AI calls"><input value={phone} onChange={e=>setPhone(e.target.value)}/></Field><button className="primary" onClick={save}>Save profile</button>{msg&&<p>{msg}</p>}</article><article><h2>Plan & usage</h2><div className="usage-row"><span>Current plan</span><b>{sub?.plan_name||'Pro'}</b></div><div className="usage-row"><span>AI requests</span><b>{sub?.ai_requests?.remaining??84} left</b></div><div className="usage-row"><span>Voice minutes</span><b>{Math.floor((sub?.voice?.remaining_seconds??1800)/60)} left</b></div><div className="usage-row"><span>Auto-Apply steps</span><b>{sub?.autoapply_calls?.remaining??280} left</b></div></article></section></>}

function initials(name=''){return name.split(' ').filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'SA'}

export default function App(){return <Routes><Route path="/sso-callback" element={<AuthenticateWithRedirectCallback/>}/><Route path="*" element={<AuthGate/>}/></Routes>}
