import { createContext, useCallback, useContext, useEffect, useState } from 'react'
import { api, errorMessage, newKey } from '@/sage/api'
import { useAuta } from '@/state'
import { useSage } from '@/sage/state'
import { Button, Card, Field, Input, Select, Textarea, Badge, Spinner } from '@/components/ui'
import { Academics } from './Academics'
import { DeckView, AssessmentPage } from './ExamPrep'

type CampusData = { profile: Record<string, any>; plans: any[]; tasks: any[]; deadlines: any[]; opportunities: any[]; assessments: any[]; analytics: Record<string, number>; catalogue: any }
const Context = createContext<{data:CampusData|null; error:string; refresh:()=>Promise<void>}>({data:null,error:'',refresh:async()=>{}})
export function CampusProvider({children}:{children:React.ReactNode}) {
 const [data,setData]=useState<CampusData|null>(null);const [error,setError]=useState('')
 const refresh=useCallback(async()=>{try{setData(await api.get('/v1/campus/workspace'));setError('')}catch(e){setError(errorMessage(e))}},[])
 useEffect(()=>{void refresh();const t=setInterval(()=>{void api.post('/v1/campus/reminders/check').then(()=>refresh()).catch(()=>{})},60000);return()=>clearInterval(t)},[refresh])
 return <Context.Provider value={{data,error,refresh}}>{children}</Context.Provider>
}
const labels:Record<string,string>={dashboard:'Your campus, in focus',jobs:'On-campus jobs',interview:'Interview AI',timetable:'Timetable & calendar',attendance:'Attendance calculator',class_recommendations:'Class priorities',semester:'Semester planner',progress:'Daily progress',activity:'Activity planner',assignments:'Assignments & pending work',fees:'Fees',internships:'Internships',workshops:'Workshops',research:'Faculty Research Partnerships',networking:'Industry networking'}
export function Campus({view}:{view:string}) {
 const {data,error,refresh}=useContext(Context)
 if(!data)return <div className="p-8 pt-14">{error?<><p role="alert">{error}</p><Button onClick={()=>void refresh()}>Retry</Button></>:<Spinner/>}</div>
 return <div className="h-full overflow-auto px-8 pb-10 pt-12"><div className="mx-auto max-w-6xl space-y-5"><header><p className="text-xs uppercase tracking-widest text-primary">BITSoM · Mumbai · {data.profile.batch ?? 2026}</p><h1 className="mt-2 text-3xl font-bold">{labels[view]}</h1><p className="mt-2 text-sm text-muted-foreground">{data.profile.target_role ?? 'Set your career goal in onboarding'} · {data.profile.daily_minutes ?? 60} minutes per day</p></header>{error&&<p role="alert" className="text-destructive">{error}</p>}
 {view==='dashboard'?<Dashboard data={data}/>:view==='attendance'?<Academics/>:view==='timetable'?<Calendar data={data}/>:['semester','activity','class_recommendations'].includes(view)?<Planner kind={view} data={data}/>:view==='progress'?<Progress data={data}/>:['assignments','fees'].includes(view)?<Deadlines fees={view==='fees'} data={data}/>:view==='interview'?<Interview data={data}/>:<Opportunities view={view} data={data}/>}
 </div></div>
}
function Metric({label,value}:{label:string;value:React.ReactNode}){return <Card className="p-5"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></Card>}
function Dashboard({data:d}:{data:CampusData}){
 const {me}=useSage();const {applications}=useAuta();const latest=d.assessments[0]
 let attendance='76.7% · demo';try{const records=JSON.parse(localStorage.getItem(`sage:bitsom:attendance:v1:${me?.user.id}`)||'null');if(records){const a=records.reduce((n:any,r:any)=>({held:n.held+r.held,attended:n.attended+r.attended}),{held:0,attended:0});attendance=a.held?`${(100*a.attended/a.held).toFixed(1)}% · demo`:'No classes'}}catch{}
 return <><p className="text-lg">Welcome back, {me?.user.full_name ?? 'Korada'}.</p><div className="grid gap-4 sm:grid-cols-4"><Metric label="Tasks complete" value={`${d.analytics.tasks_completed}/${d.analytics.tasks_total}`}/><Metric label="Progress" value={`${d.analytics.completion_percent}%`}/><Metric label="Overdue items" value={d.analytics.overdue}/><Metric label="Practice sessions" value={d.analytics.practice_sessions}/></div><div className="grid gap-4 sm:grid-cols-3"><Metric label="Latest assessed score" value={latest?`${latest.overall_score}%`:'No call yet'}/><Metric label="Target salary · aspiration" value={`₹${d.profile.salary_lpa ?? '—'} LPA`}/><Metric label="Voice minutes remaining" value={Math.floor((me?.subscription?.voice.remaining_seconds??0)/60)}/></div><Card className="p-5 space-y-3"><h2 className="font-bold">Next actions</h2>{d.tasks.filter(t=>t.status==='pending').slice(0,5).map(t=><p key={t.id} className="text-sm">{t.title} · {t.minutes} min · {date(t.due_at)}</p>)}{!d.tasks.length&&<p className="text-sm text-muted-foreground">Create a semester plan to build your daily task list.</p>}</Card><div className="grid gap-3 sm:grid-cols-3"><Metric label="Attendance · local demo" value={attendance}/><Metric label="Imported / local applications" value={applications.length}/><Metric label="Submitted applications" value={applications.filter(a=>a.status==='submitted').length}/></div><Calendar data={d}/></>
}
function date(value:string){return new Date(value).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'})}
function Calendar({data}:{data:CampusData}){
 const subjects:string[]=data.profile.subjects ?? []; const [offset,setOffset]=useState(0); const first=new Date(); first.setDate(first.getDate()-((first.getDay()+6)%7)+offset*7)
 return <Card className="space-y-4 p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Weekly calendar</h2><Badge tone="warning">Illustrative class schedule · IST</Badge></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setOffset(offset-1)}>Previous</Button><Button size="sm" variant="outline" onClick={()=>setOffset(0)}>Today</Button><Button size="sm" variant="outline" onClick={()=>setOffset(offset+1)}>Next</Button></div></div><p className="text-xs text-muted-foreground">Selected courses drive this demo schedule. Saved tasks and deadlines appear on their actual dates. No official timetable feed is connected.</p><div className="grid gap-2 lg:grid-cols-7">{Array.from({length:7},(_,i)=>{const day=new Date(first);day.setDate(first.getDate()+i);const iso=day.toLocaleDateString('en-CA');const events=[...data.tasks,...data.deadlines].filter(t=>new Date(t.due_at).toLocaleDateString('en-CA')===iso);return <div className="min-h-44 rounded-lg bg-secondary/50 p-3" key={i}><h3 className="mb-3 text-sm font-bold">{day.toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short'})}</h3>{i<6&&subjects.length>0&&[0,1].map(j=><p className="mb-3 text-xs" key={j}><strong>{j?'11:00':'09:00'}</strong><br/>{subjects[(i*2+j)%subjects.length]}</p>)}{events.map(t=><p key={t.id} className="mb-2 rounded bg-primary/10 p-2 text-xs">{t.title}<br/>{t.status}</p>)}</div>})}</div></Card>
}
function Planner({kind,data}:{kind:string;data:CampusData}){
 const {refresh}=useContext(Context);const [goal,setGoal]=useState(data.profile.career_goal??'');const [weeks,setWeeks]=useState('8');const [focus,setFocus]=useState('placements');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const latest=data.plans.find(p=>p.kind===kind)
 async function generate(){setBusy(true);setError('');try{await api.post('/v1/campus/plans',{kind,goal,weeks:Number(weeks),focus});await refresh()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 return <><Card className="p-5 space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Field label="Goal"><Input value={goal} onChange={e=>setGoal(e.target.value)}/></Field><Field label="Horizon"><Select value={weeks} onChange={e=>setWeeks(e.target.value)} options={['2','4','8','12','24'].map(v=>({value:v,label:`${v} weeks`}))}/></Field><Field label="Focus"><Select value={focus} onChange={e=>setFocus(e.target.value)} options={['placements','internships','portfolio projects','networking','academic improvement']}/></Field></div><p className="text-xs text-muted-foreground">OpenAI uses your selected courses, experience, goals and daily time budget. Salary targets are aspirations. Required attendance remains a priority.</p><Button loading={busy} disabled={goal.trim().length<3} onClick={()=>void generate()}>Plan with AI</Button>{busy&&<p className="text-xs">Creating your structured plan…</p>}{error&&<p role="alert" className="text-destructive">{error}</p>}</Card>{latest?<PlanResult output={latest.output}/>:<Card className="p-6 text-muted-foreground">Choose your goal and click Plan. Your saved plan will appear here.</Card>}</>
}
function PlanResult({output:o}:{output:any}){return <div className="space-y-4"><Card className="p-6 space-y-3"><h2 className="text-xl font-bold">{o.title}</h2><p>{o.summary}</p><p className="text-sm text-muted-foreground">{o.salary_context}</p><div className="flex gap-3"><Badge>{o.recommended_internships} internship targets</Badge><Badge>{o.recommended_projects} projects</Badge><Badge>{o.weekly_hours} hours / week</Badge></div></Card><div className="grid gap-3 sm:grid-cols-2">{o.milestones.map((m:any,i:number)=><Card key={i} className="p-4"><Badge>Week {m.week}</Badge><h3 className="mt-2 font-bold">{m.title}</h3><p className="mt-2 text-sm">Evidence: {m.evidence}</p></Card>)}</div><Card className="p-5 space-y-2"><h3 className="font-bold">Course priorities</h3>{o.class_priorities.map((s:string,i:number)=><p key={i} className="text-sm">{s}</p>)}</Card><div className="grid gap-3 sm:grid-cols-2">{o.tasks.map((t:any,i:number)=><Card className="space-y-2 p-4" key={i}><Badge>Day {t.day} · {t.minutes} min · {t.category}</Badge><h3 className="font-bold">{t.title}</h3><p className="text-sm">Deliverable: {t.deliverable}</p><p className="text-xs text-muted-foreground">Real use: {t.real_world_use}</p></Card>)}</div><Card className="p-5 text-xs text-muted-foreground">{o.assumptions.join(' · ')}</Card></div>}
function Progress({data}:{data:CampusData}){
 const {refresh}=useContext(Context);const [filter,setFilter]=useState('pending');const [error,setError]=useState('');const [busy,setBusy]=useState('')
 async function update(t:any){setBusy(t.id);try{await api.patch(`/v1/campus/tasks/${t.id}`,{status:t.status==='done'?'pending':'done',evidence:t.evidence});await refresh()}catch(e){setError(errorMessage(e))}finally{setBusy('')}}
 return <><div className="grid gap-3 sm:grid-cols-3"><Metric label="Completed" value={data.analytics.tasks_completed}/><Metric label="Completion" value={`${data.analytics.completion_percent}%`}/><Metric label="Remaining effort" value={`${data.tasks.filter(t=>t.status==='pending').reduce((n,t)=>n+t.minutes,0)} min`}/></div><p className="text-sm text-muted-foreground">At {data.profile.daily_minutes??60} minutes/day, remaining work needs at least {Math.ceil(data.tasks.filter(t=>t.status==='pending').reduce((n,t)=>n+t.minutes,0)/(data.profile.daily_minutes??60))} study days. This assumes consistent availability.</p><Select value={filter} onChange={e=>setFilter(e.target.value)} options={['pending','done','all']}/>{error&&<p role="alert">{error}</p>}{data.tasks.filter(t=>filter==='all'||t.status===filter).map(t=><Card key={t.id} className="flex items-center justify-between gap-4 p-4"><div><h3 className="font-bold">{t.title}</h3><p className="text-xs text-muted-foreground">{t.category} · {t.minutes} min · {date(t.due_at)}</p></div><Button size="sm" loading={busy===t.id} variant="outline" onClick={()=>void update(t)}>{t.status==='done'?'Reopen':'Mark done'}</Button></Card>)}{!data.tasks.length&&<p>Create a semester or activity plan first.</p>}</>
}
function Opportunities({view,data}:{view:string;data:CampusData}){
 const [query,setQuery]=useState('');const [min,setMin]=useState('0');const [location,setLocation]=useState('all');const [ranked,setRanked]=useState<any[]|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('')
 const kind=({jobs:'job',internships:'internship',workshops:'workshop',research:'research',networking:'networking'} as any)[view];let items=data.opportunities.filter(o=>o.kind===kind);const locations=Array.from(new Set(items.map(o=>o.location)))
 if(ranked)items=items.map(o=>({...o,...ranked.find(r=>r.id===o.id)})).sort((a,b)=>(b.score??0)-(a.score??0))
 items=items.filter(o=>(o.title+' '+o.organisation+' '+o.skills.join(' ')).toLowerCase().includes(query.toLowerCase())&&(!Number(min)||Number(o.salary_lpa)>=Number(min))&&(location==='all'||o.location===location))
 async function recommend(){setBusy(true);try{const r=await api.post('/v1/campus/recommendations');setRanked(r.items);setError('')}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 return <><Badge tone="warning">Synthetic demo opportunities · not live vacancies</Badge><Card className="grid gap-3 p-5 sm:grid-cols-3"><Field label="Search roles and skills"><Input value={query} onChange={e=>setQuery(e.target.value)}/></Field><Field label="Location"><Select value={location} onChange={e=>setLocation(e.target.value)} options={[{value:'all',label:'All locations'},...locations.map(v=>({value:v,label:v}))]}/></Field><Field label="Minimum salary · LPA"><Input type="number" min="0" value={min} onChange={e=>setMin(e.target.value)}/></Field>{['jobs','internships'].includes(view)&&<><Button loading={busy} onClick={()=>void recommend()}>AI Recommended Jobs</Button><Button variant="outline" onClick={()=>setRanked(null)}>All jobs</Button></>}</Card>{error&&<p role="alert" className="text-destructive">{error}</p>}<div className="grid gap-4 sm:grid-cols-2">{items.map(o=><Card className="space-y-3 p-5" key={o.id}><div className="flex justify-between"><Badge>{o.organisation}</Badge>{o.score!==undefined&&<Badge tone="primary">{o.score}% fit</Badge>}</div><h2 className="text-xl font-bold">{o.title}</h2><p className="text-sm">{o.location}{Number(o.salary_lpa)>0?` · ₹${o.salary_lpa} LPA demo`:''}</p><p className="text-sm text-muted-foreground">{o.description}</p><div className="flex flex-wrap gap-2">{o.skills.map((s:string)=><Badge key={s}>{s}</Badge>)}</div>{o.event_at&&<p className="text-xs">{date(o.event_at)}</p>}{o.explanation&&<p className="text-xs text-muted-foreground">Semantic {o.explanation.semantic}% · Salary {o.explanation.salary_alignment}% · Specialisation {o.explanation.specialisation_alignment}%. {o.explanation.weights}. {o.explanation.notice}</p>}</Card>)}</div>{!items.length&&<p>No opportunities match these filters.</p>}</>
}
function Deadlines({fees,data}:{fees:boolean;data:CampusData}){
 const {refresh}=useContext(Context);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [title,setTitle]=useState('');const [due,setDue]=useState('')
 async function act(id:string,action:string){setBusy(id);setError('');try{const r=await api.post(`/v1/campus/deadlines/${id}/${action}`,{idempotency_key:newKey()});if(r.checkout_url)await window.sage.openExternal(r.checkout_url);await refresh()}catch(e){setError(errorMessage(e))}finally{setBusy('')}}
 return <><p className="text-sm text-muted-foreground">{fees?'Demo fee checkout uses Razorpay TEST. It is not an institutional payment receipt.':'Track faculty work and deadlines. Opt-in reminders call only your own saved number, during 9 am–6 pm IST.'}</p><div className="flex gap-2"><Button variant="outline" onClick={async()=>{try{await api.post('/v1/campus/deadlines/demo');await refresh()}catch(e){setError(errorMessage(e))}}}>Load demo assignments & fees</Button><Button variant="outline" onClick={()=>void refresh()}>Refresh payment / follow-up status</Button></div>{!fees&&<Card className="grid gap-3 p-5 sm:grid-cols-3"><Field label="Assignment"><Input value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Deadline (local time)"><Input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></Field><Button disabled={title.length<2||!due} onClick={async()=>{try{await api.post('/v1/campus/deadlines',{title,category:'assignment',due_at:new Date(due).toISOString()});setTitle('');await refresh()}catch(e){setError(errorMessage(e))}}}>Add assignment</Button></Card>}{error&&<p role="alert" className="text-destructive">{error}</p>}{data.deadlines.filter(d=>fees?d.category!=='assignment':d.category==='assignment').map(d=><Card className="space-y-3 p-5" key={d.id}><div className="flex justify-between"><h3 className="font-bold">{d.title}</h3><Badge tone={d.status==='pending'?'warning':'success'}>{d.status}</Badge></div><p className="text-sm">Due {date(d.due_at)}{fees?` · ₹${(d.amount/100).toLocaleString('en-IN')}`:''}</p><p className="text-xs text-muted-foreground">{d.is_demo?'Demo · ':''}Follow-up: {d.call_status??d.reminder_state}{d.reason?` · Reason: ${d.reason}`:''}</p>{d.status==='pending'&&<Button loading={busy===d.id} onClick={()=>void act(d.id,fees?'checkout':'complete')}>{fees?'Pay with Razorpay TEST':'Mark completed'}</Button>}</Card>)}</>
}
function Interview({data}:{data:CampusData}){
 const jobs=data.opportunities.filter(j=>j.kind==='job');const [job,setJob]=useState(jobs[0]?.id??'');const [resume,setResume]=useState(data.profile.resume_summary??'');const [deck,setDeck]=useState('');const [assessment,setAssessment]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('')
 const open=(v:any)=>{if(v.name==='assessment')setAssessment(v.id);else if(v.name==='home')setDeck('')}
 if(assessment)return <AssessmentPage id={assessment} back={()=>setAssessment('')} open={open}/>
 if(deck)return <DeckView id={deck} initialTab="quiz" open={open}/>
 return <Card className="p-5 space-y-4"><Field label="On-campus role"><Select value={job} onChange={e=>setJob(e.target.value)} options={jobs.map(j=>({value:j.id,label:j.title+' · '+j.organisation}))}/></Field><Field label="Your resume facts"><Textarea rows={9} value={resume} onChange={e=>setResume(e.target.value)} maxLength={16000}/></Field><Button variant="outline" onClick={async()=>{const p=await window.auta.getProfile();if(p)setResume(JSON.stringify(p,null,2).slice(0,16000))}}>Import my AutA resume context</Button><p className="text-xs text-muted-foreground">The AI prepares questions from this resume and selected job description. Next you review the call consent and start your mock interview. No employer is contacted.</p><Button loading={busy} disabled={resume.length<30||!job} onClick={async()=>{setBusy(true);setError('');try{const d=await api.post('/v1/campus/interview',{job_id:job,resume_text:resume});setDeck(d.id)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}}>Prepare interview</Button>{error&&<p role="alert" className="text-destructive">{error}</p>}</Card>
}
export function Pricing(){
 const {me,refreshMe}=useSage();const [plans,setPlans]=useState<any[]>([]);const [busy,setBusy]=useState('');const [error,setError]=useState('')
 useEffect(()=>{void api.get('/v1/billing/plans').then(r=>setPlans(r.items)).catch(e=>setError(errorMessage(e)))},[])
 return <div className="h-full overflow-auto p-8 pt-12 space-y-6"><header><p className="text-xs text-primary">CHOOSE YOUR PACE</p><h1 className="mt-2 text-3xl font-bold">Plus, Pro & Ultra</h1><p className="mt-2 text-sm text-muted-foreground">30-day access · Razorpay TEST checkout · No automatic renewal</p></header><Badge tone="warning">Demo payment · no real money</Badge><div className="grid gap-4 lg:grid-cols-3">{plans.filter(p=>['plus','pro','ultra'].includes(p.code)).sort((a,b)=>a.price_inr_paise-b.price_inr_paise).map(p=><Card className="space-y-4 p-6" key={p.code}><h2 className="text-xl font-bold">{p.name}</h2><p className="text-4xl font-bold">₹{p.price_inr_paise/100}<span className="text-sm font-normal"> / 30 days</span></p><ul className="space-y-2 text-sm"><li>Academic dashboard, attendance & calendar</li><li>Quick Notes and semester planning</li><li>{p.ai_requests} AI generations / recommendations</li><li>{p.chat_messages} knowledge chat messages</li><li>{p.voice_minutes} AI voice minutes</li><li>{p.autoapply_calls} auto-apply agent steps</li>{p.code!=='plus'&&<><li>Semantic job recommendations</li><li>Interview AI and activity planner</li><li>Class priorities & opt-in deadline calls</li></>}</ul><Button loading={busy===p.code} onClick={async()=>{setBusy(p.code);setError('');try{const r=await api.post('/v1/billing/orders',{plan_code:p.code,idempotency_key:newKey()});await window.sage.openExternal(r.checkout_url)}catch(e){setError(errorMessage(e))}finally{setBusy('')}}}>Choose {p.name} · TEST</Button></Card>)}</div><p className="text-xs text-muted-foreground">Agent steps measure AI actions, not completed applications. Voice is shared by study, interview and follow-up calls. Allowances apply; call usage is reconciled after the call. Successful verified test checkout updates access.</p><p className="text-sm">Current access: {me?.subscription?.plan_name??'No active plan'}</p><Button variant="outline" onClick={()=>void refreshMe()}>I completed checkout · refresh access</Button>{error&&<p role="alert" className="text-destructive">{error}</p>}</div>
}
